id = "angular-tree-sitter"
name = "angular-tree-sitter"
version = "0.0.1"
schema_version = 1
authors = ["Mischa Daamen <msvdaamen@outlook.com>"]
description = "Tree sitter for angular"
repository = "https://github.com/msvdaamen/zed-angular-test"

[language_servers.angular]
name = "Angular Language Server"
language = "Angular"

[language_servers.html]
language = "HTML"

[language_servers.typescript]
language = "TypeScript"

[grammars.angular]
repository = "https://github.com/dlvandenberg/tree-sitter-angular"
commit = "31182d43b062a350d4bd2449f2fc0d5654972be9"

[grammars.typescript]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
path = "typescript"
commit = "5d20856f34315b068c41edaee2ac8a100081d259"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html.git"
commit = "e4d834eb4918df01dcad5c27d1b15d56e3bd94cd"

[language_servers.vscode-angular-language-server]
language = "Angular"
